### PR TITLE
allows adding a specific file in a folder by creating the folder first in overridesFolder

### PR DESCRIPTION
**Pull request by FederAndInk**
allows doing this:

```pwsh
$FOLDERS_TO_INCLUDE_IN_CLIENT_FILES = @(
    "dir/file"
)
```

### CODE REVIEW

**Comment by NielsPilgaard** [comment]
Oh nice, thanks for the PR :D 

Would you mind explaining what `Split-Path` does here? I don't really get it

**Comment by FederAndInk** [comment]
`split-path` by default is like `dirname` on unix, getting the parent directory of a path

windows command names sucks

**Comment by FederAndInk** [comment]
> Oh nice, thanks for the PR :D

Thanks, no problem :+1: 

here is the doc too: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/split-path?view=powershell-7.2#example-3-get-the-parent-container

<blockquote><div><strong><a href="https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/split-path">Split-Path (Microsoft.PowerShell.Management) - PowerShell</a></strong></div><div>The Split-Path cmdlet returns only the specified part of a path, such as the parent folder, a subfolder, or a file name. It can also get items that are referenced by the split path and tell whether the path is relative or absolute. You can use this cmdlet to get or submit only a selected part of a path. </div></blockquote>

**Review by NielsPilgaard — APPROVED** [review]
Thanks, looks good to me 👍

**Pull request merged**
